
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 13;
  public static final int MULTIPLICACAO = 16;
  public static final int CHAVEESQ = 23;
  public static final int ELSE = 7;
  public static final int CHAVEDIR = 24;
  public static final int IGUAL = 20;
  public static final int OR = 14;
  public static final int INT = 4;
  public static final int WHILE = 27;
  public static final int NOT = 12;
  public static final int OPMAIOR = 18;
  public static final int RETORNO = 11;
  public static final int IF = 6;
  public static final int ID = 9;
  public static final int VIRGULA = 26;
  public static final int CONSTANTE = 8;
  public static final int EOF = 0;
  public static final int MAIN = 28;
  public static final int PARESQ = 21;
  public static final int OPMENOR = 19;
  public static final int PARDIR = 22;
  public static final int error = 1;
  public static final int NUMERO = 10;
  public static final int OPIGUAL = 17;
  public static final int BOOL = 3;
  public static final int CLASSE = 2;
  public static final int SOMA = 15;
  public static final int PONTOEVIRGULA = 25;
  public static final int VOID = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASSE",
  "BOOL",
  "INT",
  "VOID",
  "IF",
  "ELSE",
  "CONSTANTE",
  "ID",
  "NUMERO",
  "RETORNO",
  "NOT",
  "AND",
  "OR",
  "SOMA",
  "MULTIPLICACAO",
  "OPIGUAL",
  "OPMAIOR",
  "OPMENOR",
  "IGUAL",
  "PARESQ",
  "PARDIR",
  "CHAVEESQ",
  "CHAVEDIR",
  "PONTOEVIRGULA",
  "VIRGULA",
  "WHILE",
  "MAIN"
  };
}

